
export const Sidebar2 = () => {
    return (
        <div className="fixed overflow-y-auto left-[1500px] h-[680px] w-[150px] border-[2px] border-red-900">
            <div>Calendar</div>
            <div>Chark</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>
            <div>Map</div>

        </div>
    )
}